### ISSUE TITLE
Error in selecting range with large files.

### ISSUE THREAD

**Issue by anubhavmalik** [knowledge4life/k4l-video-trimmer#59]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - k4l-video-trimmer version: `1.0.3`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `Lenovo`
 - Device Name: `Vibe K5 Plus`
 
###### Reproduction Steps
1. SetMaxDuration as 30 seconds
2. Choose a large sized video. Say 2 hours (A movie or something)
3. Move the range seek bar to ends of the movie, the max duration will increase and not remain 30 seconds (visually).

###### Expected Result
A trimmed file of 30 seconds duration

###### Actual Result
A trimmed file of 2 - 3 minutes
### Tell us what could be improved:

**Comment by anubhavmalik** [comment]
I have fixed the issue and forced the duration at setMax length. Will probably create a PR sometime in the future.

**Comment by aashitshah26** [comment]
Hey what changes have you done ?
