### ISSUE TITLE
CancelClicked  should call VideoView.stopPlayback

### ISSUE THREAD

**Issue by gouravd** [knowledge4life/k4l-video-trimmer#9]
I think cancelClicked should do a bit of cleanup
1) stop VideoView playback

Also it would be helpful if VideoView is exposed so that we can control some other aspects like its visibility etc..

In my use case the Trimmer is housed in a RelativeLayout and stays hidden. When required we make the RelLayout visible and set URI. But if we click cancel, there is no way to stop the video and hide the videoView. Hiding the Relativelayout does not help because our background is a GLSurfaceView and the Zorder thing messes things up.

Currently I have edited the Trimmer to make VideoView visible on setURI and stop playback & invisible on CancelClicked

**Comment by dogo** [comment]
Yep! Thanks @gouravd the cancel action should stop the video playback, about expose some other aspects would be nice, you can open a PR proposing those changes
